### ISSUE TITLE
May be dumb but how tf can we patch amfi without restoring

### ISSUE THREAD

**Issue by danni551** [elihwyma/Pogo#4]
I tried using Ramiel for patches but it wants to wipe my data lol
I a just giving up I'm waiting for geosnow this is real poop shit :)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by itsnebulalol** [comment]
https://github.com/itsnebulalol/palera1n
