### ISSUE TITLE
Root password not accepted

### ISSUE THREAD

**Issue by bobmarleyfaruk9** [elihwyma/Pogo#7]
Hi,

I am not really sure if this is a problem related to Pogo, if its not, feel free to close this issue.
After installing sileo and using sileo to install openssh, I cant ssh into the device.
It is asking me for root password which should be alpine but its not working. I dont think I have changed the password in the past but just to be sure I dumped the /private/etc/master.passwd file using custom ssh ramdisk.

localhost:/etc root# cat master.passwd
##
# User Database
#
# This file is the authoritative user database.
##
nobody:*:-2:-2::0:0:Unprivileged User:/var/empty:/usr/bin/false
root:/smx7MYTQIi2M:0:0::0:0:System Administrator:/var/root:/bin/sh
mobile:/smx7MYTQIi2M:501:501::0:0:Mobile User:/var/mobile:/bin/sh
daemon:*:1:1::0:0:System Services:/var/root:/usr/bin/false
_ftp:*:98:-2::0:0:FTP Daemon:/var/empty:/usr/bin/false
.....

which is the default as seen here
https://opensource.apple.com/source/files/files-638.1.4/private/etc/master.passwd.iPhone

is this an issue related Pogo ? Or is sshing with a ramdisk somehow different?
I have tried connecting by iproxy, termius etc.

My setup: iPhone X, iOS 15.1 Pogo build(5ebbd54)

**Comment by elihwyma** [comment]
Honestly I'm not quite sure where the issue is with this, it's one I've experienced as well. A workaround for now is login as mobile with alpine and then su to root. I'll leave this issue open for now

**Comment by itsnebulalol** [comment]
For me, changing the root password to something works.

This can also be done in Pogo, probably. The sudo binary needs to be replaced with spawn_root.

**Comment by mineek** [comment]
If u add my repo, mineek.github.io/repo, and download the "sudoworking" package, you can use sudo, from there just ssh in as mobile and sudo passwd, then you can use the root user.

**Comment by elihwyma** [comment]
> If u add my repo, mineek.github.io/repo, and download the "sudoworking" package, you can use sudo, from there just ssh in as mobile and sudo passwd, then you can use the root user.

This is the cause of the issue: https://github.com/elihwyma/Pogo/pull/8#issuecomment-1257051905
