### ISSUE TITLE
can filza work as root using that ?

### ISSUE THREAD

**Issue by dualra1n** [elihwyma/Pogo#9]
can i install filza

**Comment by itsnebulalol** [comment]
what?

**Comment by dualra1n** [comment]
> what?

because i dont need inyect code only i want to use filza, and filza has access root

**Comment by itsnebulalol** [comment]
i mean sure, you can edit the filza daemon plist and move files around, but i don’t see how this is related to Pogo

you can install filza with TrollStore for /var rw

**Comment by dualra1n** [comment]
> 

oh thank I did not know that you can use trollstore to install that so thank bro
